services:
  - type: web
    name: alignai-backend
    env: python
    buildCommand: "cd backend && ./build.sh"
    startCommand: "gunicorn -c gunicorn_config.py app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000 