services:
  - type: web
    name: alignai-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn -c gunicorn_config.py app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 